linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - govet
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
    - goimports
    - gosec
    - interfacer
    # - lll
    # - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - thelper
    - unconvert
    - unparam

linters-settings:
  exhaustive:
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  gocritic:
    enabled-tags:
      - style
      - diagnostic
    disabled-checks:
      - nestingReduce
      - sloppyReassign
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 10
  govet:
    # report about shadowed variables
    check-shadowing: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - prealloc
        - scopelint
